# Generated by Django 3.1.10 on 2021-05-15 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20210514_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('bytes_sent', models.FloatField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='websites.website')),
            ],
            options={
                'ordering': ['datetime'],
                'get_latest_by': 'datetime',
            },
        ),
    ]
