# Generated by Django 3.1.10 on 2021-05-15 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_datapoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'get_latest_by': 'date_logged', 'ordering': ['date_logged']},
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='datetime',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='date_logged',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='url',
            field=models.CharField(default='/', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='bytes_sent',
            field=models.PositiveBigIntegerField(),
        ),
    ]
