# Generated by Django 3.1.10 on 2021-05-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_auto_20210515_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='hits',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
