# Generated by Django 3.1.10 on 2021-05-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_datapoint_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='log_type',
            field=models.CharField(choices=[('1', 'APACHE'), ('2', 'NGINX')], default='1', max_length=32),
        ),
    ]
