# Generated by Django 3.1.10 on 2021-05-25 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_auto_20210525_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='date_logged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
